default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 15 } %>
  timeout: 5000

development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>_dev

test:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>_test


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

